### ISSUE TITLE
Remove images and left over files (in .get) after a repo/app has been removed (or an app has been removed from the repo)

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [vgmoose/libget#13]

**Comment by vgmoose** [comment]
This is a pretty low priority for me personally, (about the cached images in `./get/tmp/cache`?) I don't think it's a major deal to clean that up. Even the "clear cache" button in the credits screen in hb-appstore [only deletes the version json data](https://github.com/vgmoose/hb-appstore/blob/master/gui/AboutScreen.cpp#L95) and leaves behind images. (Which i think is alright since these are pretty small images that don't take up much space)

But if someone wants to do it, they're free to-- I'd imagine this change would go in hb-appstore itself (since it maintains the image cache), and you would know which folders to delete by comparing the list of files in `./get/tmp/cache` to the current package list.

I think #8 is a more needed change though.

**Comment by vgmoose** [comment]
Well the cache concern is gone, as we’ve removed the cache!

Tmp files are also cleaned up after install. As of 2.2 there shouldn’t be any files left behind besides manifests, which are needed

**Comment by vgmoose** [comment]
(Manifests can be cleared via recovery mode, however)
